name = "SIAN"
uuid = "cf7bdac0-b945-4905-b5ad-bc3f1a757483"
authors = ["Ilia Ilmer <i.ilmer@icloud.com>", "Alexey Ovchinnikov <Alexey.Ovchinnikov@qc.cuny.edu>", "Gleb Pogudin <gleb.pogudin@polytechnique.edu>"]
version = "1.0.3"

[deps]
GroebnerBasis = "e39c9192-ea4d-5e15-9584-a488c6d614bd"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
Singular = "bcd08a7b-43d2-5ff7-b6d4-c458787f915c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestSetExtensions = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"

[compat]
GroebnerBasis = "0.1, 0.2, 0.3"
MacroTools = "0.5"
OrderedCollections = "1.3"
Oscar = "0.5, 0.6"
Singular = "0.4, 0.5, 0.6, 0.7"
TestSetExtensions = "2.0.0"
julia = "1.5, 1.6"
