name = "SIAN"
uuid = "cf7bdac0-b945-4905-b5ad-bc3f1a757483"
authors = ["Ilia Ilmer <i.ilmer@icloud.com>", "Alexey Ovchinnikov <Alexey.Ovchinnikov@qc.cuny.edu>", "Gleb Pogudin <gleb.pogudin@polytechnique.edu>"]
version = "1.8.0"

[deps]
Groebner = "0b43b601-686d-58a3-8a1c-6623616c7cd4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StructuralIdentifiability = "220ca800-aa68-49bb-acd8-6037fa93a544"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"


[compat]
Groebner = "0.9, 0.10"
MacroTools = "0.5"
ModelingToolkit = "11"
Nemo = "0.40 - 0.54"
OrderedCollections = "1"
SpecialFunctions = "1, 2"
StructuralIdentifiability = "0.5"
SymbolicUtils = "4"
TestSetExtensions = "2"
LinearAlgebra = "1.0 - 2.0"
Logging = "1.0 - 2.0"
Test = "1.0 - 2.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestSetExtensions = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"

[targets]
test = ["Test", "TestSetExtensions"]
