name = "SIAN"
uuid = "cf7bdac0-b945-4905-b5ad-bc3f1a757483"
authors = ["Ilia Ilmer <i.ilmer@icloud.com>", "Alexey Ovchinnikov <Alexey.Ovchinnikov@qc.cuny.edu>", "Gleb Pogudin <gleb.pogudin@polytechnique.edu>"]
version = "1.4.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Groebner = "0b43b601-686d-58a3-8a1c-6623616c7cd4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StructuralIdentifiability = "220ca800-aa68-49bb-acd8-6037fa93a544"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestSetExtensions = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"

[compat]
BenchmarkTools = "1"
Groebner = "0.2"
MacroTools = "0.5"
ModelingToolkit = "6, 7, 8"
Nemo = "0.22, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.30, 0.31, 0.32, 0.33"
OrderedCollections = "1.3"
SpecialFunctions = "1, 2"
StructuralIdentifiability = "0.4"
SymbolicUtils = "0.18, 0.19, 1"
TestSetExtensions = "2"
julia = "1"
